"use client";

import { AnchorProvider, Program } from "@coral-xyz/anchor";
import { useAnchorWallet, useConnection } from "@solana/wallet-adapter-react";
import { PublicKey } from "@solana/web3.js";
import { PROGRAM_ID } from "@/config/solana";
import { useMemo } from "react";

// Import IDL - this file should be copied from target/idl/onchain_gift_cards.json after building
import idl from "./idl.json";

const IDL = idl as any;

// This assumes the IDL will be generated by Anchor
// You may need to adjust the path based on where Anchor generates the IDL
// Common locations: 
// - target/idl/onchain_gift_cards.json
// - target/types/onchain_gift_cards.ts

export function useProgram() {
  const { connection } = useConnection();
  const wallet = useAnchorWallet();

  const program = useMemo(() => {
    if (!wallet || !IDL) return null;

    const provider = new AnchorProvider(connection, wallet, {
      commitment: "confirmed",
    });

    return new Program(IDL, provider);
  }, [connection, wallet]);

  return program;
}

// Helper function to get gift card PDA with card_id for multiple cards support
export function getGiftCardPDA(owner: PublicKey, cardId: bigint, programId: PublicKey): [PublicKey, number] {
  // Buffer is available in Node.js environments and modern browsers
  const giftCardSeed = typeof Buffer !== "undefined" 
    ? Buffer.from("gift_card") 
    : new Uint8Array([103, 105, 102, 116, 95, 99, 97, 114, 100]); // "gift_card" as bytes
  
  // Convert cardId to little-endian 8-byte array (u64)
  const cardIdBytes = new Uint8Array(8);
  let tempCardId = cardId;
  for (let i = 0; i < 8; i++) {
    cardIdBytes[i] = Number(tempCardId & BigInt(0xff));
    tempCardId = tempCardId >> BigInt(8);
  }
  
  return PublicKey.findProgramAddressSync(
    [giftCardSeed, owner.toBuffer(), cardIdBytes],
    programId
  );
}

// Generate a unique card ID based on timestamp and random number
export function generateCardId(): bigint {
  const timestamp = BigInt(Date.now());
  const random = BigInt(Math.floor(Math.random() * 1000000));
  return timestamp * BigInt(1000000) + random;
}
